#pragma once

#include "FoTypes.h"

enum CoGameCmdType
{
	CGC_FRAME 		= 0,
	CGC_PLAYER_INFO,
	CGC_LOAD,
	CGC_START,
	CGC_END,
	CGC_CHART_PLAYER,
	CGC_RACEBET_RESULT,
	
	CGC_PLAYER_LEAVE,
	CGC_SYSTEM_SUSPEND,
	CGC_SYSTEM_CHEAT,
	CGC_RACE_PAUSE,
	CGC_PAUSE_CANCEL,
	CGC_SYSTEM_SURRENDER,
	
	CGC_HERO_DIRECT_MOVE,
	CGC_HERO_MOVE,
	CGC_UNIT_MOVE,
	CGC_HERO_STOP,
	CGC_UNIT_STOP,
	CGC_HERO_HOLD,
	CGC_UNIT_HOLD,
	CGC_HERO_ATTACK_POS,
	CGC_HERO_ATTACK_UNIT,
	CGC_UNIT_ATTACK,
	CGC_UNIT_PATROL,
	CGC_UNIT_FOLLOW,
	CGC_UNIT_SPELL,
	CGC_UNIT_SPELLSING,
	CGC_UNIT_USE_ITEM,
	CGC_UNIT_USE_DIR_ITEM,
	CGC_UNIT_PICK_ITEM,
	CGC_UNIT_PICK_ITEM_AUTO,
	CGC_UNIT_BUY_ITEM,
	CGC_UNIT_DIRECTBUY_ITEM,
	CGC_UNIT_DIRECTSELL_ITEM,
	CGC_UNIT_SWAP_ITEM,
	CGC_UNIT_LEARN_SKILL,
	CGC_UNIT_ACTIVE_SKILL,
	CGC_UNIT_DISPLACE_ITEM,
	CGC_UNIT_GIVEUP_DISPLACE_ITEM,
	CGC_UNIT_SUPER_SKILL,

	CGC_WATCH_POINT,
	CGC_SHOP_LIST,

	CGC_PLAYER_RELIVEHERO,
	CGC_PLAYER_LEVEL_CMD,

	CGC_PLAYER_TOWNITEM,
	CGC_PLAYER_RECON_BEGIN,
	CGC_PLAYER_RECON_END,

	CGC_VIEW_SELHERO,
	CGC_SWITCH_HEROFOCUS,

	CGC_PAUSE_BEGIN,
	CGC_PAUSE_END,

	CGC_LOCK_UNIT,
	CGC_ADJUST_FRAME,
	
	CGC_RELINK_BEGIN,
	CGC_RELINK_END,
	CGC_TRAN_LOADEND,
	CGC_SWICH_MODE,
	CGC_PING,
	CGC_SAVE_RECONDATA_BEGIN,
	CGC_SAVE_RECONDATA_END,



	CGC_REPLAY_VERSION,

	CPGC_UNIT_DISAPPEAR,
	CPGC_KILLHERO_DATA,
	CPGC_DAMAGE_DATA,
	CPGC_HERO_DATA,
	CPGC_MAP_ITEM_DATA,
	CPGC_ATTACH_DATA,
	CPGC_EFFECT_DATA,
	CPGC_EFFECTDEL_DATA,
	CPGC_UI_DATA,
	CPGC_UNITSHOW_DATA,
	CPGC_GLOBAL_DATA,
	CPGC_PING,
	CPGC_USER_DATA,
	CPGC_MAPPOINT_DATA,
	CPGC_VISION_DATA,
	CPGC_MAPMESSAGE_DATA,
};

struct CoGameCmd
{
	CoGameCmd(CoGameCmdType eCmd = CGC_FRAME, uint32 frame = 0) : uiFrame(frame),uiSeat(0),uiQueue(0),uiCmd(eCmd)
	{
	}

	uint32 uiFrame:16;
	uint32 uiSeat:5;
	uint32 uiQueue:1;
	uint32 uiCmd:7;
};

struct CoGameFrame : public CoGameCmd
{
	CoGameFrame():CoGameCmd(CGC_FRAME) {}
};


